spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: ${ACTIVEMQ_URL:tcp://localhost:61616}
server:
  port: 8083
active-mq:
  funds-transfer: ${FUNDS-TRANSFER:funds-transfer}
  cash-deposit: ${CASH-DEPOSIT:cash-deposit}
  withdrawals: ${WITHDRAWALS:withdrawals}